name: Publish Python Package

on:
  push:
    branches:
      - main # action trigger when a new commit added to main branch

jobs:
  publish:
    # The job will run on the latest Ubuntu environment
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository so the workflow can access the code
      - name: Check out repository
        uses: actions/checkout@v4
      # Step 2: Set up Python environment (install the specified version of Python)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9 # Set your desired Python version

      # Step 3: Install dependencies (pip, build, twine)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build twine

      # Step 4: Build the package
      - name: Build package
        run: python -m build

      # Step 5: Upload the built package to PyPI using Twine
      - name: Upload package to PyPI
        run: python -m twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
